### ISSUE TITLE
Desktop/web support

### ISSUE THREAD

**Issue by smachave** [NotSimone/Dex-Reader#1]
Hello,

Thank you for making this. I was looking for a tool which I could use to read on my desktop. Since this is made using flutter, does it also support the desktop/web target?

-Saurabh

**Comment by NotSimone** [comment]
Web target UI is a bit dodgy with scrolling pages but it should be working now. Main issue is that CORS isnt enabled (yet) on the API right now so it needs to be proxied.

Take a look here: https://dexreader.simonliveshere.com/#/

**Comment by smachave** [comment]
Thank you so much! That's amazing 🚀 

It works well on Chrome 👍
